# Generated by Django 5.1.4 on 2024-12-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_status",
            field=models.BooleanField(
                default=False, verbose_name="Email Verification Status"
            ),
        ),
    ]
