# Generated by Django 5.1.4 on 2024-12-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0004_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
